# ------------------------------------------------------------------------------------------------ #
#                                             CONSTANTS                                            #
# ------------------------------------------------------------------------------------------------ #

DATA_FILE_PATH = "./data/dvf.csv"
DATA_SEP_CHAR = ","
DATA_CHUNK_SIZE = 200_000
DATA_CLEAN_FILE_PATH = "./data/dvf_clean.csv"

DATA_DATE_COLUMN = "date_mutation"
DATA_NATURE_MUTATION_COLUMN = "nature_mutation"
DATA_VALEUR_FONCIERE_COLUMN = "valeur_fonciere"
DATA_ADRESSE_NUMERO_COLUMN = "adresse_numero"
DATA_ADRESSE_SUFFIXE_COLUMN = "adresse_suffixe"
DATA_ADRESSE_NOM_VOIE_COLUMN = "adresse_nom_voie"
DATA_CODE_POSTAL_COLUMN = "code_postal"
DATA_CODE_COMMUNE_COLUMN = "code_commune"
DATA_NOM_COMMUNE_COLUMN = "nom_commune"
DATA_CODE_DEPARTEMENT_COLUMN = "code_departement"
DATA_CODE_TYPE_LOCAL_COLUMN = "code_type_local"
DATA_TYPE_LOCAL_COLUMN = "type_local"
DATA_SURFACE_REELLE_COLUMN = "surface_reelle_bati"
DATA_NB_PIECES_COLUMN = "nombre_pieces_principales"
DATA_SURFACE_TERRAIN_COLUMN = "surface_terrain"
DATA_LONGITUDE_COLUMN = "longitude"
DATA_LATITUDE_COLUMN = "latitude"
DATA_TIME_COLUMN = "Jours_depuis"
DATA_YEAR_COLUMN = "annee"
DATA_MONTH_COLUMN = "mois"
DATA_CODE_POSTAL_TREND_6M_COLUMN = "commune_trend_6m"
DATA_CODE_POSTAL_MEAN_6M_COLUMN = "commune_mean_6m"

DATA_CLASS_COLUMNS = [
	DATA_YEAR_COLUMN,
	DATA_MONTH_COLUMN,
	DATA_CODE_POSTAL_COLUMN
]
DATA_CLASS_SIZE = 100
DATA_SIZE = 100_000

DATA_NATURE_MUTATION_VENTE_VALUE = "Vente"
DATA_TYPE_LOCAL_VALUE = [
	"Appartement", "Maison"
]

DATA_COLUMNS = [
	DATA_DATE_COLUMN,
	DATA_NATURE_MUTATION_COLUMN,
	DATA_VALEUR_FONCIERE_COLUMN,
	DATA_ADRESSE_NUMERO_COLUMN,
	DATA_ADRESSE_SUFFIXE_COLUMN,
	DATA_ADRESSE_NOM_VOIE_COLUMN,
	DATA_CODE_POSTAL_COLUMN,
	DATA_CODE_COMMUNE_COLUMN,
	DATA_NOM_COMMUNE_COLUMN,
	DATA_CODE_DEPARTEMENT_COLUMN,
	DATA_CODE_TYPE_LOCAL_COLUMN,
	DATA_TYPE_LOCAL_COLUMN,
	DATA_SURFACE_REELLE_COLUMN,
	DATA_NB_PIECES_COLUMN,
	DATA_SURFACE_TERRAIN_COLUMN,
	DATA_LONGITUDE_COLUMN,
	DATA_LATITUDE_COLUMN
]

DATA_IMPORTANT_COLUMNS = [
	DATA_DATE_COLUMN,
	DATA_NATURE_MUTATION_COLUMN,
	DATA_VALEUR_FONCIERE_COLUMN,
	DATA_CODE_POSTAL_COLUMN,
	DATA_SURFACE_REELLE_COLUMN,
	DATA_NB_PIECES_COLUMN,
	DATA_SURFACE_TERRAIN_COLUMN,
	DATA_LONGITUDE_COLUMN,
	DATA_LATITUDE_COLUMN,
]

DATA_CLEAN_COLUMNS = [
	DATA_DATE_COLUMN,
	DATA_VALEUR_FONCIERE_COLUMN,
	DATA_CODE_POSTAL_COLUMN,
	DATA_TYPE_LOCAL_COLUMN,
	DATA_SURFACE_REELLE_COLUMN,
	DATA_NB_PIECES_COLUMN,
	DATA_SURFACE_TERRAIN_COLUMN,
	DATA_LONGITUDE_COLUMN,
	DATA_LATITUDE_COLUMN
]

DATA_MAIN_CLASSES = [
	DATA_DATE_COLUMN,
	DATA_VALEUR_FONCIERE_COLUMN,
	DATA_CODE_POSTAL_COLUMN,
	DATA_TYPE_LOCAL_COLUMN,
	DATA_SURFACE_REELLE_COLUMN,
	DATA_NB_PIECES_COLUMN,
	DATA_SURFACE_TERRAIN_COLUMN,
	DATA_LONGITUDE_COLUMN,
	DATA_LATITUDE_COLUMN
]

XGB_MODEl_PATH = "./models/xgb"
XGB_TEST_SET_PATH = "./models/xgb_test"
CAT_MODEl_PATH = "./models/cat"
CAT_TEST_SET_PATH = "./models/cat_test"

DATA_COLUMNS_STR = {column: column for column in DATA_MAIN_CLASSES}
DATA_COLUMNS_STR[DATA_SURFACE_REELLE_COLUMN] = "Surface réelle"

GEO_DATA_REGIONS = [11.]

# ------------------------------------------------------------------------------------------------ #